type Query { 
  products: [String]
  customProduct(title: String!): String!
}

input ProductInput {
  name: String
  price: Int
}

type Product {
  name: String
  price: Int
}

type Mutation {
  addProduct(product: ProductInput): Product
}
